travis:
  secure:
    BINSTAR_TOKEN: L7ngTvv9ci/Cy32bm3BO1PN0kI1asvnzMkLJ+SPZmpY186WkwG5zKuLsewURBSt6Uiogx1cnAMVtiG9Y46peHpwo09LLThI5NqixtlGQ3CcjIpjqgB9ezFm9lMRAknWAHRu9CqECtoCA4dAkInKr7TdJnPGrlsFclbniBJ+u47AqgbHFEUcGCCvPiTJWxp/F2wihxSkqZuTiBm28HRc7UISxWLQrNkGNIBbQMO8I3Cw18wFFwxsRZmX37/NX7Eo+SmN5oQUP3ainiMZyVvFTYqJxIhedkvufvS/3w4bIhS/4HVzFI1YHHbicfkRU8eDZU5myoh7rLK8SHSWkktZBUZTjPLO5Rf2sWbed49dDbpV+prCm4Tu7DJfGfnYssd0ghJvppJN0aBUApKQqXIGwC2BCdjA4q6yjQQnwu0ZEws20FMKGKQW/cv9KamycGEjct1RVPUcsZ+uGzakQeChGA8VP/Xq8hdf57OyZr9jQBepU8nl1d83pNO6JQCmRKKhiiqeNg8EnpgYJwTy0zvdAY6fTLEfGIHBwqDKUIaeKil8GEDTgnwEcpyudJRPs8gSRCFwr1l16ao5Q4motryySEUCgWrXyjX3uEtyxfOfk3sPyK0r/JAzoeLc8dhecSvn/0vB5B2rgNct+Utfyr0oUpo7fzgmy3Q8Nrcr7AMxmSP0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
